### ISSUE TITLE
Change all "url" methods to "path"

### ISSUE THREAD

**Issue by hmoradian** [pincoin/rakmai#2]
Hello,
Change all "url" methods to "path" and "re_path" method to all urls.py files.
This action is very simple:
*  Change this line in head of all "urls.py" files: 
        from django.conf.urls import url   -> from django.urls import path
*  Change all "url" words to "path" or "re_path" for using regex
*  Change first arguments to simple url, example: r'^(?P&lt;store&gt;[-\w]+)/$'  ->  '&lt;store&gt;/'
        or:  r'^(?P&lt;book&gt;\d+)/(?P&lt;page&gt;\d+)/feedback$' 
 ->  '&lt;int:book&gt;/&lt;int:page&gt;/feedback'
        and etc...
*  Meanwhile, if you want to do this, I can do it for you :)

Thanks again

**Comment by hmoradian** [comment]
Meanwhile, if you want to do this, I can do it for you.
tnx

**Comment by pincoin** [comment]
Hello,

Actually, I used "url" for backward compatibility and I remember that there were several issues with "path". I think I will have to examine and test more before we change "url" to "path".

Let me make this issue open and keep my eys on this issue in order to change smoothly.

Thank you.

**Comment by hmoradian** [comment]
Hi,
As you know, the use of a path is more readable for humans. In some cases,
it is also compulsory to use "re_path" for use of regex instead of the
"path", such as the four digit for year and two digit for the month and
day, with "url" syntax. In addition, it also increases the speed of loading
routes.
Thanks

**Comment by hmoradian** [comment]
Hello my friend,
Thank you very much for this changes (url to path)

**Comment by pincoin** [comment]
@hmoradian 

Hello,

I didn't think you're still watching my repo. I just changed them all into the style of django 2.0 or above.

I will close this issue. Thank you.

ps. Unfortunately both teams failed to go forward to the final of Asian Cup. :-(
